### ISSUE TITLE
Get a new URL for zupoll

### ISSUE THREAD

**Issue by vb7401** [proofcarryingdata/zupoll#11]

**Comment by ichub** [comment]
![Image](https://user-images.githubusercontent.com/2636237/233444910-a1cc6328-e57c-49f7-94d1-073531063297.png)
![Image](https://user-images.githubusercontent.com/2636237/233444909-3e28fcd6-3ba7-4603-99f0-90ab3ba40a92.png)


zupoll.org incoming

**Comment by ichub** [comment]
done
