### ISSUE TITLE
Disable NONANON endpoint to prevent double voting.

### ISSUE THREAD

**Issue by sampritipanda** [proofcarryingdata/zupoll#25]
Right now the backend allows a user to submit a vote as NONANON even though there is no frontend support for it. Let's just disable it for now (by throwing a error or something like that).

**Comment by vb7401** [comment]
I've decided to just remove this logic from the repository right now. We have no UI to test this right now, and I'm fine adding it back if we actually decide NONANON polls are a feature we'd like to support.
