### ISSUE TITLE
Need to make the returned polls payload smaller + paginated

### ISSUE THREAD

**Issue by vb7401** [proofcarryingdata/zupoll#7]
Right now, the `/polls` endpoint on `zupoll-server` returns all the polls and all of their votes, along with their PCDs. This will massively balloon once we have many polls with hundreds of votes, and likely lead to massive slowdowns in places with poor internet (for example, 200 people in the Dome voting on a poll all downloading all of this information).

These results are then tabulated on the client-side, and the proofs aren't even verified. So we should for sure remove all the PCDs attached, and likely also just return a `PollResult` payload where the results are tabulated on the server.

**Comment by sampritipanda** [comment]
smaller payload is done
